### ISSUE TITLE
revalidateFn: README.md example incorect?

### ISSUE THREAD

**Issue by jgchristian** [yahoo/storage-lru#14]
Following the examples in the README.md, I specified options.revalidateFn as part of the setItem call, e.g.
```javascript
lru.setItem('fooJSON',{foo: 'bar'},
    { 
        json: true,
        cacheControl:'max-age=10,stale-while-revalidate=20',
        revalidateFn: function(key, callback) {
            console.log("revalidateFn called.");
        }
    }, function (err) {}
    }
);
```

However, I never this this revalidate function being called.

Looking in to the source, it appears that you should actually set this when creating the StorageLRU instance, rather than on the setItem call

e.g.

```javascript
var lru = new StorageLRU(asyncify(localStorage), 
    { revalidateFn: function(key, callback) {
        console.log("revalidateFn called.");
    }
});
```

This seems to get fired as expected.

Not sure if this is intended, so I didn't create a pull request on the README.md until I confirmed with you.

J

**Comment by lingyan** [comment]
@jgchristian You are absolutely correct.  Nice catch!

The description is README is correct, but the code example is clearly wrong :(  Please go ahead create a PR.  I'll be more than happy to merge it.

Thanks!
